version: '3.5'

services:
  database:
    image: postgres:alpine
    container_name: "database"
    hostname: "database"
    restart: always
    networks:
      - dev_network
    ports:
      - 5432:5432
    env_file:
      - ./db/.env
    volumes:
      - ./db/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - 5432

  cache:
    image: redis:alpine
    container_name: "cache"
    hostname: "cache"
    restart: always
    ports:
      - 6379:6379
    networks:
      - dev_network

  s3:
    image: bitnami/minio:latest
    container_name: "s3"
    ports:
      - 9000:9000
    environment:
      - MINIO_ACCESS_KEY=minio-access-key
      - MINIO_SECRET_KEY=minio-secret-key
    networks:
      - dev_network

  adminer:
    image: adminer:latest
    container_name: "adminer"
    restart: always
    networks:
      - dev_network
    depends_on:
      - database
    ports:
      - 8000:8080
    expose:
      - 8000

  app:
    build:
      context: ..
      dockerfile: ./dev/app.dockerfile
    container_name: "app"
    env_file:
      - ./db/.env
    depends_on:
      - database
      - cache
      - s3
    volumes:
      - ../src:/usr/local/app/src
    networks:
      - dev_network
    ports:
      - 8080:8080
    expose:
      - 8080
      - 5432
      - 9000
    command: ["make", "watch-app"]

networks:
  dev_network:
    name: dev_network
